"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ThrowException = exports.Error524ATimeoutOccurred = exports.Error522ConnectionTimedOut = exports.Error520WebServerIsReturningAnUnknownError = exports.Error511NetworkAuthenticationRequired = exports.Error505HTTPVersionNotSupported = exports.Error504GatewayTimeout = exports.Error503ServiceUnavailable = exports.Error502BadGateway = exports.Error501NotImplemented = exports.Error500InternalServerError = exports.Error451UnavailableForLegalReasons = exports.Error431RequestHeaderFieldsTooLarge = exports.Error429TooManyRequests = exports.Error428PreconditionRequired = exports.Error422UnprocessableEntity = exports.Error421MisdirectedRequest = exports.Error418ImaTeapot = exports.Error417ExpectationFailed = exports.Error416RequestedRangeNotSatisfiable = exports.Error415UnsupportedMediaType = exports.Error414RequestURITooLong = exports.Error413RequestEntityTooLarge = exports.Error412PreconditionFailed = exports.Error411LengthRequired = exports.Error410Gone = exports.Error409Conflict = exports.Error408RequestTimeout = exports.Error407ProxyAuthenticationRequired = exports.Error406NotAcceptable = exports.Error405MethodNotAllowed = exports.Error404NotFound = exports.Error403Forbidden = exports.Error402PaymentRequired = exports.Error401Unauthorized = exports.Error400BadRequest = exports.Error308PermanentRedirect = exports.Error307TemporaryRedirect = exports.Error306Unused = exports.Error305UseProxy = exports.Error304NotModified = exports.Error303SeeOther = exports.Error302Found = exports.Error301MovedPermanently = exports.ThrowNetworkConnectionException = exports.NetworkConnectionException = exports.RestClientBaseException = void 0;
var base_exception_1 = require("./base.exception");
Object.defineProperty(exports, "RestClientBaseException", { enumerable: true, get: function () { return __importDefault(base_exception_1).default; } });
var network_connection_exception_1 = require("./network.connection.exception");
Object.defineProperty(exports, "NetworkConnectionException", { enumerable: true, get: function () { return __importDefault(network_connection_exception_1).default; } });
var throw_network_connection_exception_1 = require("./throw.network.connection.exception");
Object.defineProperty(exports, "ThrowNetworkConnectionException", { enumerable: true, get: function () { return __importDefault(throw_network_connection_exception_1).default; } });
var error_301_moved_permanently_1 = require("./error.301.moved.permanently");
Object.defineProperty(exports, "Error301MovedPermanently", { enumerable: true, get: function () { return __importDefault(error_301_moved_permanently_1).default; } });
var error_302_found_1 = require("./error.302.found");
Object.defineProperty(exports, "Error302Found", { enumerable: true, get: function () { return __importDefault(error_302_found_1).default; } });
var error_303_see_other_1 = require("./error.303.see.other");
Object.defineProperty(exports, "Error303SeeOther", { enumerable: true, get: function () { return __importDefault(error_303_see_other_1).default; } });
var error_304_not_modified_1 = require("./error.304.not.modified");
Object.defineProperty(exports, "Error304NotModified", { enumerable: true, get: function () { return __importDefault(error_304_not_modified_1).default; } });
var error_305_use_proxy_1 = require("./error.305.use.proxy");
Object.defineProperty(exports, "Error305UseProxy", { enumerable: true, get: function () { return __importDefault(error_305_use_proxy_1).default; } });
var error_306_unused_1 = require("./error.306.unused");
Object.defineProperty(exports, "Error306Unused", { enumerable: true, get: function () { return __importDefault(error_306_unused_1).default; } });
var error_307_temporary_redirect_1 = require("./error.307.temporary.redirect");
Object.defineProperty(exports, "Error307TemporaryRedirect", { enumerable: true, get: function () { return __importDefault(error_307_temporary_redirect_1).default; } });
var error_308_permanent_redirect_1 = require("./error.308.permanent.redirect");
Object.defineProperty(exports, "Error308PermanentRedirect", { enumerable: true, get: function () { return __importDefault(error_308_permanent_redirect_1).default; } });
var error_400_bad_request_1 = require("./error.400.bad.request");
Object.defineProperty(exports, "Error400BadRequest", { enumerable: true, get: function () { return __importDefault(error_400_bad_request_1).default; } });
var error_401_unauthorized_1 = require("./error.401.unauthorized");
Object.defineProperty(exports, "Error401Unauthorized", { enumerable: true, get: function () { return __importDefault(error_401_unauthorized_1).default; } });
var error_402_payment_required_1 = require("./error.402.payment.required");
Object.defineProperty(exports, "Error402PaymentRequired", { enumerable: true, get: function () { return __importDefault(error_402_payment_required_1).default; } });
var error_403_forbidden_1 = require("./error.403.forbidden");
Object.defineProperty(exports, "Error403Forbidden", { enumerable: true, get: function () { return __importDefault(error_403_forbidden_1).default; } });
var error_404_not_found_1 = require("./error.404.not.found");
Object.defineProperty(exports, "Error404NotFound", { enumerable: true, get: function () { return __importDefault(error_404_not_found_1).default; } });
var error_405_method_not_allowed_1 = require("./error.405.method.not.allowed");
Object.defineProperty(exports, "Error405MethodNotAllowed", { enumerable: true, get: function () { return __importDefault(error_405_method_not_allowed_1).default; } });
var error_406_not_acceptable_1 = require("./error.406.not.acceptable");
Object.defineProperty(exports, "Error406NotAcceptable", { enumerable: true, get: function () { return __importDefault(error_406_not_acceptable_1).default; } });
var error_407_proxy_authentication_required_1 = require("./error.407.proxy.authentication.required");
Object.defineProperty(exports, "Error407ProxyAuthenticationRequired", { enumerable: true, get: function () { return __importDefault(error_407_proxy_authentication_required_1).default; } });
var error_408_request_timeout_1 = require("./error.408.request.timeout");
Object.defineProperty(exports, "Error408RequestTimeout", { enumerable: true, get: function () { return __importDefault(error_408_request_timeout_1).default; } });
var error_409_conflict_1 = require("./error.409.conflict");
Object.defineProperty(exports, "Error409Conflict", { enumerable: true, get: function () { return __importDefault(error_409_conflict_1).default; } });
var error_410_gone_1 = require("./error.410.gone");
Object.defineProperty(exports, "Error410Gone", { enumerable: true, get: function () { return __importDefault(error_410_gone_1).default; } });
var error_411_length_required_1 = require("./error.411.length.required");
Object.defineProperty(exports, "Error411LengthRequired", { enumerable: true, get: function () { return __importDefault(error_411_length_required_1).default; } });
var error_412_precondition_failed_1 = require("./error.412.precondition.failed");
Object.defineProperty(exports, "Error412PreconditionFailed", { enumerable: true, get: function () { return __importDefault(error_412_precondition_failed_1).default; } });
var error_413_request_entity_too_large_1 = require("./error.413.request.entity.too.large");
Object.defineProperty(exports, "Error413RequestEntityTooLarge", { enumerable: true, get: function () { return __importDefault(error_413_request_entity_too_large_1).default; } });
var error_414_request_uri_too_long_1 = require("./error.414.request.uri.too.long");
Object.defineProperty(exports, "Error414RequestURITooLong", { enumerable: true, get: function () { return __importDefault(error_414_request_uri_too_long_1).default; } });
var error_415_unsupported_media_type_1 = require("./error.415.unsupported.media.type");
Object.defineProperty(exports, "Error415UnsupportedMediaType", { enumerable: true, get: function () { return __importDefault(error_415_unsupported_media_type_1).default; } });
var error_416_requested_range_not_satisfiable_1 = require("./error.416.requested.range.not.satisfiable");
Object.defineProperty(exports, "Error416RequestedRangeNotSatisfiable", { enumerable: true, get: function () { return __importDefault(error_416_requested_range_not_satisfiable_1).default; } });
var error_417_expectation_failed_1 = require("./error.417.expectation.failed");
Object.defineProperty(exports, "Error417ExpectationFailed", { enumerable: true, get: function () { return __importDefault(error_417_expectation_failed_1).default; } });
var error_418_im_a_teapot_1 = require("./error.418.im.a.teapot");
Object.defineProperty(exports, "Error418ImaTeapot", { enumerable: true, get: function () { return __importDefault(error_418_im_a_teapot_1).default; } });
var error_421_misdirected_request_1 = require("./error.421.misdirected.request");
Object.defineProperty(exports, "Error421MisdirectedRequest", { enumerable: true, get: function () { return __importDefault(error_421_misdirected_request_1).default; } });
var error_422_unprocessable_entity_1 = require("./error.422.unprocessable.entity");
Object.defineProperty(exports, "Error422UnprocessableEntity", { enumerable: true, get: function () { return __importDefault(error_422_unprocessable_entity_1).default; } });
var error_428_precondition_required_1 = require("./error.428.precondition.required");
Object.defineProperty(exports, "Error428PreconditionRequired", { enumerable: true, get: function () { return __importDefault(error_428_precondition_required_1).default; } });
var error_429_too_many_requests_1 = require("./error.429.too.many.requests");
Object.defineProperty(exports, "Error429TooManyRequests", { enumerable: true, get: function () { return __importDefault(error_429_too_many_requests_1).default; } });
var error_431_request_headers_fields_too_large_1 = require("./error.431.request.headers.fields.too.large");
Object.defineProperty(exports, "Error431RequestHeaderFieldsTooLarge", { enumerable: true, get: function () { return __importDefault(error_431_request_headers_fields_too_large_1).default; } });
var error_451_unavailable_for_legal_reasons_1 = require("./error.451.unavailable.for.legal.reasons");
Object.defineProperty(exports, "Error451UnavailableForLegalReasons", { enumerable: true, get: function () { return __importDefault(error_451_unavailable_for_legal_reasons_1).default; } });
var error_500_internal_server_error_1 = require("./error.500.internal.server.error");
Object.defineProperty(exports, "Error500InternalServerError", { enumerable: true, get: function () { return __importDefault(error_500_internal_server_error_1).default; } });
var error_501_not_implemented_1 = require("./error.501.not.implemented");
Object.defineProperty(exports, "Error501NotImplemented", { enumerable: true, get: function () { return __importDefault(error_501_not_implemented_1).default; } });
var error_502_bad_gateway_1 = require("./error.502.bad.gateway");
Object.defineProperty(exports, "Error502BadGateway", { enumerable: true, get: function () { return __importDefault(error_502_bad_gateway_1).default; } });
var error_503_service_unavailable_1 = require("./error.503.service.unavailable");
Object.defineProperty(exports, "Error503ServiceUnavailable", { enumerable: true, get: function () { return __importDefault(error_503_service_unavailable_1).default; } });
var error_504_gateway_timeout_1 = require("./error.504.gateway.timeout");
Object.defineProperty(exports, "Error504GatewayTimeout", { enumerable: true, get: function () { return __importDefault(error_504_gateway_timeout_1).default; } });
var error_505_http_version_not_supported_1 = require("./error.505.http.version.not.supported");
Object.defineProperty(exports, "Error505HTTPVersionNotSupported", { enumerable: true, get: function () { return __importDefault(error_505_http_version_not_supported_1).default; } });
var error_511_network_authentication_required_1 = require("./error.511.network.authentication.required");
Object.defineProperty(exports, "Error511NetworkAuthenticationRequired", { enumerable: true, get: function () { return __importDefault(error_511_network_authentication_required_1).default; } });
var error_520_web_server_is_returning_an_unknown_error_1 = require("./error.520.web.server.is.returning.an.unknown.error");
Object.defineProperty(exports, "Error520WebServerIsReturningAnUnknownError", { enumerable: true, get: function () { return __importDefault(error_520_web_server_is_returning_an_unknown_error_1).default; } });
var error_522_connection_timed_out_1 = require("./error.522.connection.timed.out");
Object.defineProperty(exports, "Error522ConnectionTimedOut", { enumerable: true, get: function () { return __importDefault(error_522_connection_timed_out_1).default; } });
var error_524_a_timeout_occurred_1 = require("./error.524.a.timeout.occurred");
Object.defineProperty(exports, "Error524ATimeoutOccurred", { enumerable: true, get: function () { return __importDefault(error_524_a_timeout_occurred_1).default; } });
var throw_exception_1 = require("./throw.exception");
Object.defineProperty(exports, "ThrowException", { enumerable: true, get: function () { return __importDefault(throw_exception_1).default; } });
