"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RestClient = exports.MockRestClient = exports.ThrowNetworkConnectionException = exports.ThrowException = exports.Error524ATimeoutOccurred = exports.Error522ConnectionTimedOut = exports.Error520WebServerIsReturningAnUnknownError = exports.Error511NetworkAuthenticationRequired = exports.Error505HTTPVersionNotSupported = exports.Error504GatewayTimeout = exports.Error503ServiceUnavailable = exports.Error502BadGateway = exports.Error501NotImplemented = exports.Error500InternalServerError = exports.Error451UnavailableForLegalReasons = exports.Error431RequestHeaderFieldsTooLarge = exports.Error429TooManyRequests = exports.Error428PreconditionRequired = exports.Error422UnprocessableEntity = exports.Error421MisdirectedRequest = exports.Error418ImaTeapot = exports.Error417ExpectationFailed = exports.Error416RequestedRangeNotSatisfiable = exports.Error415UnsupportedMediaType = exports.Error414RequestURITooLong = exports.Error413RequestEntityTooLarge = exports.Error412PreconditionFailed = exports.Error411LengthRequired = exports.Error410Gone = exports.Error409Conflict = exports.Error408RequestTimeout = exports.Error407ProxyAuthenticationRequired = exports.Error406NotAcceptable = exports.Error405MethodNotAllowed = exports.Error404NotFound = exports.Error403Forbidden = exports.Error402PaymentRequired = exports.Error401Unauthorized = exports.Error400BadRequest = exports.Error308PermanentRedirect = exports.Error307TemporaryRedirect = exports.Error306Unused = exports.Error305UseProxy = exports.Error304NotModified = exports.Error303SeeOther = exports.Error302Found = exports.Error301MovedPermanently = exports.NetworkConnectionException = exports.RestClientBaseException = void 0;
var exceptions_1 = require("./exceptions");
Object.defineProperty(exports, "RestClientBaseException", { enumerable: true, get: function () { return exceptions_1.RestClientBaseException; } });
Object.defineProperty(exports, "NetworkConnectionException", { enumerable: true, get: function () { return exceptions_1.NetworkConnectionException; } });
Object.defineProperty(exports, "Error301MovedPermanently", { enumerable: true, get: function () { return exceptions_1.Error301MovedPermanently; } });
Object.defineProperty(exports, "Error302Found", { enumerable: true, get: function () { return exceptions_1.Error302Found; } });
Object.defineProperty(exports, "Error303SeeOther", { enumerable: true, get: function () { return exceptions_1.Error303SeeOther; } });
Object.defineProperty(exports, "Error304NotModified", { enumerable: true, get: function () { return exceptions_1.Error304NotModified; } });
Object.defineProperty(exports, "Error305UseProxy", { enumerable: true, get: function () { return exceptions_1.Error305UseProxy; } });
Object.defineProperty(exports, "Error306Unused", { enumerable: true, get: function () { return exceptions_1.Error306Unused; } });
Object.defineProperty(exports, "Error307TemporaryRedirect", { enumerable: true, get: function () { return exceptions_1.Error307TemporaryRedirect; } });
Object.defineProperty(exports, "Error308PermanentRedirect", { enumerable: true, get: function () { return exceptions_1.Error308PermanentRedirect; } });
Object.defineProperty(exports, "Error400BadRequest", { enumerable: true, get: function () { return exceptions_1.Error400BadRequest; } });
Object.defineProperty(exports, "Error401Unauthorized", { enumerable: true, get: function () { return exceptions_1.Error401Unauthorized; } });
Object.defineProperty(exports, "Error402PaymentRequired", { enumerable: true, get: function () { return exceptions_1.Error402PaymentRequired; } });
Object.defineProperty(exports, "Error403Forbidden", { enumerable: true, get: function () { return exceptions_1.Error403Forbidden; } });
Object.defineProperty(exports, "Error404NotFound", { enumerable: true, get: function () { return exceptions_1.Error404NotFound; } });
Object.defineProperty(exports, "Error405MethodNotAllowed", { enumerable: true, get: function () { return exceptions_1.Error405MethodNotAllowed; } });
Object.defineProperty(exports, "Error406NotAcceptable", { enumerable: true, get: function () { return exceptions_1.Error406NotAcceptable; } });
Object.defineProperty(exports, "Error407ProxyAuthenticationRequired", { enumerable: true, get: function () { return exceptions_1.Error407ProxyAuthenticationRequired; } });
Object.defineProperty(exports, "Error408RequestTimeout", { enumerable: true, get: function () { return exceptions_1.Error408RequestTimeout; } });
Object.defineProperty(exports, "Error409Conflict", { enumerable: true, get: function () { return exceptions_1.Error409Conflict; } });
Object.defineProperty(exports, "Error410Gone", { enumerable: true, get: function () { return exceptions_1.Error410Gone; } });
Object.defineProperty(exports, "Error411LengthRequired", { enumerable: true, get: function () { return exceptions_1.Error411LengthRequired; } });
Object.defineProperty(exports, "Error412PreconditionFailed", { enumerable: true, get: function () { return exceptions_1.Error412PreconditionFailed; } });
Object.defineProperty(exports, "Error413RequestEntityTooLarge", { enumerable: true, get: function () { return exceptions_1.Error413RequestEntityTooLarge; } });
Object.defineProperty(exports, "Error414RequestURITooLong", { enumerable: true, get: function () { return exceptions_1.Error414RequestURITooLong; } });
Object.defineProperty(exports, "Error415UnsupportedMediaType", { enumerable: true, get: function () { return exceptions_1.Error415UnsupportedMediaType; } });
Object.defineProperty(exports, "Error416RequestedRangeNotSatisfiable", { enumerable: true, get: function () { return exceptions_1.Error416RequestedRangeNotSatisfiable; } });
Object.defineProperty(exports, "Error417ExpectationFailed", { enumerable: true, get: function () { return exceptions_1.Error417ExpectationFailed; } });
Object.defineProperty(exports, "Error418ImaTeapot", { enumerable: true, get: function () { return exceptions_1.Error418ImaTeapot; } });
Object.defineProperty(exports, "Error421MisdirectedRequest", { enumerable: true, get: function () { return exceptions_1.Error421MisdirectedRequest; } });
Object.defineProperty(exports, "Error422UnprocessableEntity", { enumerable: true, get: function () { return exceptions_1.Error422UnprocessableEntity; } });
Object.defineProperty(exports, "Error428PreconditionRequired", { enumerable: true, get: function () { return exceptions_1.Error428PreconditionRequired; } });
Object.defineProperty(exports, "Error429TooManyRequests", { enumerable: true, get: function () { return exceptions_1.Error429TooManyRequests; } });
Object.defineProperty(exports, "Error431RequestHeaderFieldsTooLarge", { enumerable: true, get: function () { return exceptions_1.Error431RequestHeaderFieldsTooLarge; } });
Object.defineProperty(exports, "Error451UnavailableForLegalReasons", { enumerable: true, get: function () { return exceptions_1.Error451UnavailableForLegalReasons; } });
Object.defineProperty(exports, "Error500InternalServerError", { enumerable: true, get: function () { return exceptions_1.Error500InternalServerError; } });
Object.defineProperty(exports, "Error501NotImplemented", { enumerable: true, get: function () { return exceptions_1.Error501NotImplemented; } });
Object.defineProperty(exports, "Error502BadGateway", { enumerable: true, get: function () { return exceptions_1.Error502BadGateway; } });
Object.defineProperty(exports, "Error503ServiceUnavailable", { enumerable: true, get: function () { return exceptions_1.Error503ServiceUnavailable; } });
Object.defineProperty(exports, "Error504GatewayTimeout", { enumerable: true, get: function () { return exceptions_1.Error504GatewayTimeout; } });
Object.defineProperty(exports, "Error505HTTPVersionNotSupported", { enumerable: true, get: function () { return exceptions_1.Error505HTTPVersionNotSupported; } });
Object.defineProperty(exports, "Error511NetworkAuthenticationRequired", { enumerable: true, get: function () { return exceptions_1.Error511NetworkAuthenticationRequired; } });
Object.defineProperty(exports, "Error520WebServerIsReturningAnUnknownError", { enumerable: true, get: function () { return exceptions_1.Error520WebServerIsReturningAnUnknownError; } });
Object.defineProperty(exports, "Error522ConnectionTimedOut", { enumerable: true, get: function () { return exceptions_1.Error522ConnectionTimedOut; } });
Object.defineProperty(exports, "Error524ATimeoutOccurred", { enumerable: true, get: function () { return exceptions_1.Error524ATimeoutOccurred; } });
Object.defineProperty(exports, "ThrowException", { enumerable: true, get: function () { return exceptions_1.ThrowException; } });
Object.defineProperty(exports, "ThrowNetworkConnectionException", { enumerable: true, get: function () { return exceptions_1.ThrowNetworkConnectionException; } });
var classes_1 = require("./classes");
Object.defineProperty(exports, "MockRestClient", { enumerable: true, get: function () { return classes_1.MockRestClient; } });
Object.defineProperty(exports, "RestClient", { enumerable: true, get: function () { return classes_1.RestClient; } });
